### PR TITLE
Align features to cover those of old File_Adapter; renaming to File_Adapter

### LINKED ISSUE #79: Rename solution, project files and namespaces to match with the renaming to `File_Toolkit`
#### Broken rules:

This repository will be renamed to `File_Toolkit` and its adapter to `File_Adapter`.
This renaming will need to go in parallel with the removal of the old `File_Adapter` that is contained in the [BHoM_Adapter](https://github.com/BHoM/BHoM_Adapter).

#### Suggestions to restore compliance:

As above.

### LINKED ISSUE #80: Add new adapter constructor that takes `string defaultFilename, string defaultDirectory` to match the one in File_Adapter
#### Description:

Once the Filing_Toolkit is renamed to File_Toolkit, we want to ensure that its functionality is entirely compatible with the old File_Adapter scripts. To do this, we need an additional constructor that matches the existing one in the File_Adapter.

### PR DESCRIPTION
**Pull request by alelom**
### NOTE: Depends on 

https://github.com/BHoM/BHoM_Adapter/pull/264

### Issues addressed by this PR

Closes #79
Closes #80
Closes https://github.com/BHoM/Filing_Toolkit/issues/85

### Test files

All existing test files for File_Adapter and Filing_Toolkit must still work.

Please go through at least these:
https://burohappold.sharepoint.com/:f:/s/BHoM/Eub2dT2Mb85Dtvv0Y09T1I4B7pzFZHcVr5NCXRuAdSpGUQ?e=h2pDm8

⚠️ If you had compiled the Filing_Toolkit before this PR, **make sure you manually delete all existing Filing_Toolkit dlls from Program Data**, because a rename happened in this PR, so the old Filing_Adapter.dll etc are not deleted. This will not be an issue when deployed from the installer (because it cleans the entire ProgramData folder).

### Changelog

- Renamed to File_Adapter, File_Engine, File_oM (from "Filing").
- Aligned features to replicate those of old File_Adapter as much as possible. Exceptions:
   - to push Datasets, this new FileAdapter requires a specific PushConfig input with DatasetSerialization set to true. 
   - removed support for BSON as problematic and actually never worked/used. If requested, may be re-added later.
- When pushing file content, the `CreateOnly` PushType will make the adapter append content to any existing file [as explained here](https://github.com/BHoM/Filing_Toolkit/pull/86#issuecomment-723243863).
- Switch from Regex to WildcardPattern. More reliable and simpler. Only admits `*` symbol, and only in the filenames. See [here](https://github.com/BHoM/Filing_Toolkit/pull/86#issuecomment-724085540).

### Additional comments

* ⚠️ Before merging this, we will need a separate PR on the base BHoM_Adapter that deletes the File_Adapter.  
I will need to raise that later, as there are other PRs that need merging before that.
* ⚠️To push Datasets, this new FileAdapter requires a specific PushConfig input with `DatasetSerialization` set to `true`. The Dataset serialisation is not proper JSON - although its extension is `.json` - so by default is set to `false`. The Library_Engine has not been updated to accept real JSON yet.

This PR replaces https://github.com/BHoM/Filing_Toolkit/pull/81 for CI to pick correct branch name.

### CODE REVIEW

**Review by michaelhoehn — APPROVED** [review]
Approving from a functionality perspective. I was able to run through all provided test files and have a quick test of typical uses with success.

**Comment by alelom** [comment]
@michaelhoehn I have done a simple fix for a bug - mind having a quick look again to approve? thanks!

**Comment by alelom** [comment]
@IsakNaslundBh would be great to get your review too

**Comment by IsakNaslundBh** [comment]
> @michaelhoehn I have done a simple fix for a bug - mind having a quick look again to approve? thanks!
> @IsakNaslundBh would be great to get your review too

The particular bug you talk about here seem to be fixed for me.

Good to mention as well, that to properly test this against older scripts, you need to manually delete all Filing_Toolkit dlls, (oM/Engine/Adapter) from Program data as the renaming means the old ones are not overwritten. Only an issue when building from source ofc, as the installer will clean it up, but though worth mentioning

**Review by IsakNaslundBh — COMMENTED** [review]
Push and pull assuming the old file adapter style, of giving a location to the file adapter itself, and just pushing BHoMObjects, seem to be working as expected.

The only word of caution would be if this is used to generate datasets. The Library_Engine has _not_ been updated to accept real json, but is still assuming the line separated format. If the default values for the action config is used, when trying to generate a dataset, you will get something that the library engine can not handle basically.

Not saying that should be a blocker from merging this, just flagging that it needs to be communicated clearly to the development team.

**Comment by alelom** [comment]
@IsakNaslundBh thanks for the comments. Updated the PR text; also I will communicate the Dataset serialisation thing on teams.

**Review by al-fisher — CHANGES_REQUESTED** [review]
`CreateOnly` PushType - "appending content to file" - is not working for me

See set up below - toggling both bool back and forth I get the same result

image

**Comment by al-fisher** [comment]
> The Library_Engine has not been updated to accept real json, but is still assuming the line separated format. If the default values for the action config is used, when trying to generate a dataset, you will get something that the library engine can not handle basically.

@IsakNaslundBh thanks for highlighting above
Agreed with your and @alelom's approach.

Have we a plan to update Library engine (and all datasets naturally) to adapt valid json?
Be good to raise an issue such that this can be agreed and planned at some point in future

This will mean ultimately we can remove this "dataset" option from the File_Adapter completely - which will simply things.

**Comment by alelom** [comment]
Note that the difficulty in appending content is also that we need to check that we are appending to the same format.
I.e. you cannot push "BHoM-Dataset" text to a valid Json file, and vice-versa.
Adding a test file for that. The behaviour of the File_Adapter will be to raise error in either scenario.

**Comment by alelom** [comment]
From my tests, now everything appears fixed/working as requested from last request for changes.

## Notable changes

### Appending mechanism
The "appending" mechanism is now more complex as it handles what [explained here](https://github.com/BHoM/Filing_Toolkit/pull/86#issuecomment-723243863).
However it seems to work fine. It also handles correctly Beautified/normal JSON.

### Switch from Regex to WildcardPattern
Additionally, I have switched from `Regex` to `WildcardPattern`. It is a more restrictive choice (it allows only `*` symbols) but it's way more reliable in this context. 
Reason is, we need to process the path to check if it's a valid path; PLUS we need to detect whether the filepath contains regex symbols or not. This is tricky to do in the first place; add that this has to be done both for Sharepoint and File_Adapter paths, so it becomes basically impossible to make it work with both URLs/FileSystem paths.

### Usage of wildcard
Further, to simplify the code, the wildcard is only admitted for filenames, not directory names. E.g.
- `C:\temp\*.json` --> valid wildcard usage
- `C:\*\somefile.json` --> invalid wildcard usage, will throw error

It is possible to admit also the second, but it would require a non negligible amount of development time.

File: File_Adapter/FileAdapter.cs [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+        /***************************************************/
+
+        // Checks on the file extension.
+        private bool ProcessExtension(ref string filePath)
+        {
+            string ext = Path.GetExtension(filePath);
+
+            if (!Path.HasExtension(m_defaultFilePath))
+            {
+                Engine.Reflection.Compute.RecordWarning($"No extension specified in the FileName input. Defaulting to .json.");
```
Comment (al-fisher) [inline File_Adapter/FileAdapter.cs:118]:
```suggestion
                Engine.Reflection.Compute.RecordNote($"No extension specified in the FileName input. Defaulting to .json.");
```

Comment (al-fisher) [reply File_Adapter/FileAdapter.cs:118]: @alelom I would downgrade this here as think this might be a prevalent assumption in File Adapter usage across scripts - and think fine to not raise as warning

**Comment by al-fisher** [comment]
Appending is now working fine - raised a small comment above - but looking good now

File: File_Adapter/FileAdapter.cs (hunk 1 above)
Comment (alelom) [reply File_Adapter/FileAdapter.cs]: Sorry - forgot to change that. Applied suggestion.

**Review by al-fisher — DISMISSED** [review]

**Comment by al-fisher** [comment]
Approving - issues above addressed - thanks @alelom - and both File (and historic Filing) workflows working

**Review by FraserGreenroyd — APPROVED** [review]
Happy from a CI perspective in the renaming call that the last commit only affects CI, so no functionality changes since @al-fisher  last reviewed
